=== H3rn4nLB-LAB/Ejercicios-Segundo-Trimestre/XML_XSD/index/biblioteca.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://w3.org">


  <xs:element name="biblioteca">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="libro" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="titulo" type="xs:string"/>
              <xs:element name="autor" type="xs:string"/>
              <xs:element name="paginas" type="xs:positiveInteger"/>
              <xs:element name="disponible" type="xs:boolean"/>
            </xs:sequence>
  
            <xs:attribute name="id" type="xs:string" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== H3rn4nLB-LAB/Ejercicios-Segundo-Trimestre/XML_XSD/index/biblioteca.xml
<?xml version="1.0" encoding="UTF-8"?>
<biblioteca xmlns:xsi="http://w3.org"
            xsi:noNamespaceSchemaLocation="biblioteca.xsd">
    <libro id="L001">
        <titulo>Don Quijote de la Mancha</titulo>
        <autor>Miguel de Cervantes</autor>
        <paginas>1032</paginas>
        <disponible>true</disponible>
    </libro>
    <libro id="L002">
        <titulo>Cien años de soledad</titulo>
        <autor>Gabriel García Márquez</autor>
        <paginas>471</paginas>
        <disponible>false</disponible>
    </libro>
</biblioteca>
