=== H3rn4nLB-LAB/Ejercicios-Segundo-Trimestre/XML_DTD/index/DAW.dtd
<!ELEMENT daw (modulo+)>
<!ELEMENT modulo (nombre, descripcion, codigo, profesor, fechas)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT codigo (#PCDATA)>
<!ELEMENT profesor (#PCDATA)>
<!ELEMENT fechas (inicio, fin)>
<!ELEMENT fin (dia, mes, ano)>
<!ELEMENT dia (#PCDATA)>
<!ELEMENT mes (#PCDATA)>
<!ELEMENT ano (#PCDATA)>

=== H3rn4nLB-LAB/Ejercicios-Segundo-Trimestre/XML_DTD/index/DAW.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE daw SYSTEM "DAW.dtd">
<daw> 
  <modulo>
    <nombre>Lenguajes de marcas y sistemas de gestion de informacion</nombre>
    <descripcion>Estudio de HTML, CSS, XML, etc.</descripcion>
    <codigo>LMSGI</codigo>
    <profesor>José Ignacio</profesor>
    <fechas>
      <inicio>
        <dia>15</dia>
        <mes>09</mes>
        <ano>2025</ano>
      </inicio>
      <fin>
        <dia>22</dia>
        <mes>06</mes>
        <ano>2026</ano>
      </fin>
    </fechas>
  </modulo>

  <modulo>
    <nombre>Desarrollo web en entorno cliente</nombre>
    <descripcion>Programación con Javascript.</descripcion>
    <codigo>DWEC</codigo>
    <profesor>María García</profesor>
    <fechas>
      <inicio>
        <dia>15</dia>
        <mes>09</mes>
        <ano>2025</ano>
      </inicio>
      <fin>
        <dia>22</dia>
        <mes>06</mes>
        <ano>2026</ano>
      </fin>
    </fechas>
  </modulo>
</daw>
