=== H3rn4nLB-LAB/Ejercicios-Segundo-Trimestre/XML_DTD/index/pedidos.dtd
<!ENTITY MiEmpresa "Esta es mi Empresa">

<!ELEMENT lista_pedidos (pedido+)>


<!ELEMENT pedido ((empresa | persona), producto+, fecha, factura?)>

<!ELEMENT empresa (#PCDATA)>
<!ATTLIST empresa 
    CIF ID #REQUIRED
    sector NMTOKEN #IMPLIED
    actividad NMTOKENS #IMPLIED>

<!ELEMENT persona (#PCDATA)>
<!ATTLIST persona 
    NIF ID #REQUIRED>

<!ELEMENT producto (#PCDATA)>
<!ATTLIST producto 
    id_prod ID #REQUIRED>

<!ELEMENT fecha (#PCDATA)>


<!ELEMENT factura (emisor, total, fecha)>
<!ATTLIST factura 
    numfactura ID #REQUIRED
    cliente IDREF #REQUIRED
    productos IDREFS #REQUIRED>

<!ELEMENT emisor (#PCDATA)>
<!ELEMENT total (#PCDATA)>

=== H3rn4nLB-LAB/Ejercicios-Segundo-Trimestre/XML_DTD/index/pedidos.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE lista_pedidos SYSTEM "pedidos.dtd">

<lista_pedidos>
  
    <pedido>
        <empresa CIF="E12345678" sector="Tecnologia" actividad="Venta_Equipos Consultoria_IT">
            Tech Solutions S.L.
        </empresa>
        <producto id_prod="P01">Portátil Pro</producto>
        <producto id_prod="P02">Ratón Óptico</producto>
        <fecha>2023-10-25</fecha>
        <factura numfactura="F001" cliente="E12345678" productos="P01 P02">
            <emisor>&MiEmpresa;</emisor>
            <total>1250.50</total>
            <fecha>2023-10-26</fecha>
        </factura>
    </pedido>

  
    <pedido>
        <persona NIF="P99887766K">Carlos Rodríguez</persona>
        <producto id_prod="P03">Teclado Mecánico</producto>
        <fecha>2023-10-27</fecha>
   
    </pedido>
</lista_pedidos>
